# This version have staging and seed directories, staging store all transformations to be
# done on the data before running the models, and the seeds directory have auxiliary tables 
# and data, like a date table on day granularity and other external sources.
name: 'superstore_dw'
version: '3.0.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'superstore_dw'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  superstore_dw:
    # Config indicated by + and applies to all files under models/example/
    +materialized: table
    staging:
      +schema: staging

seeds:
  +schema: staging

snapshots:
  superstore_dw:
    +target_schema: "snapshots"