version: 2

sources:
  - name: norm
    database: group3
    schema: norm
    tables:
     - name: t_employee
     - name: t_order
     - name: t_customer
     - name: t_segment
     - name: t_city
     - name: t_region
     - name: t_state
     - name: t_country
     - name: orders

models:
  - name: stg_employee
    description: "First employee dimension, proxy for region and date"
    columns:
      - name: employee_id
        description: "A unique identifier for the employee"
        tests:
          - unique
          - not_null
      - name: employee_name
        description: "The name of the employee"
      - name: region
        description: "The region this employee is responsible for"
  - name: d_date
    description: "Dimension table for Date, related to fact table for Orders."
    columns:
      - name: order_id
        description: "Order id, same as in normalized table, this key should be gone on later versions, It needs to be a key for each day in YEARMODA format"
        tests:
          - unique
          - not_null
      - name: order_date
        description: "The date of each order, still order granularity, that is wrong."
  - name: d_customer
    description: "Dimension table for Customer, related to fact table Orders."
    columns:
      - name: customer_id
        description: "Customer ID from normalized customer table"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Customer name from normalized customer table"
      - name: segment
        description: "Segment name, from normalized segment table"
      - name: valid_from
        description: "As SCD2, data from customer may change over time, this is the start time for this tuple"
      - name: valid_to
        description: "As SCD2, data from customer may change over time, this is the end time for this tuple"
  - name: d_location
    description: "dimension table from normalized location tables, at maximum granularity of city"
    columns:
      - name: city_id
        description: "City ID as in the normalized tables"
        tests:
          - unique
          - not_null
      - name: city_name
        description: "City name, as in the normalized tables"
      - name: region_name
        description: "Region names, if any, as in normalized tables"
      - name: state_name
        description: "State name, if any, as in normalized tables"
      - name: country_name
        description: "Country name, as in normalized tables"
  - name: f_order_row
    description: "fact table for order rows, used for query on order_id"
    columns:
      - name: row_id
        description: "This is the ID from the source order table"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "This is the key for dates present in each order"
      - name: customer_id
        description: "This is the key for customer"
      - name: city_id
        description: "This is the key for location"
      - name: ship_date
      - name: ship_mode
      - name: postal_code
      - name: product_id
      - name: category
      - name: sub_category
      - name: product_name
      - name: sales
      - name: quantity
      - name: discount
      - name: profit
