version: 2

sources:
  - name: norm
    database: group3
    schema: norm
    tables:
     - name: t_employee
     - name: t_region

models:
  - name: stg_employee
    description: "First employee dimension, proxy for region and date"
    columns:
      - name: employee_id
        description: "A unique identifier for the employee"
        tests:
          - unique
          - not_null
      - name: employee_name
        description: "The name of the employee"
      - name: region
        description: "The region this employee is responsible for"
  - name: d_date
    description: "Dimension table for Date, related to fact table for Orders."
    columns:
      - name: order_id
        description: "Order id, same as in normalized table"
        tests:
          - unique
          - not_null
      - name: order_date
        description: "The date of each order."
      